# Generated by Django 6.0.4 on 2026-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='news_media/'),
        ),
    ]
